name: Understanding Myself
favicon: null
layout_spectrum: 0.38982031657360494
typography_spectrum: 0.527480733813718
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5da9c4'
    - '#b54873'
    - '#e9e600'
    - '#bcb77d'
    - '#000200'
  brandStrength: 0.6875
  lightness: 0.24655774096027017
  saturation: 0.4107331393752247
  rhythmicContrast: 0.3643040470778942
purpose: []
